name: Sync to Hugging Face
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Ramireddy-ai:$HF_TOKEN@huggingface.co/spaces/Ramireddy-ai/transitlyiq HEAD:main
